    print ("     MON     ")
    print ("    Math     ")
    print ("9:10 to 10:15")
    print ("-------------")
    print ("   Science   ")
    print ("10:35 to 11:40")
    print ("-------------")
    print ("      PF     ")
    print ("12:10 to 1:15")